services:
  - type: web
    name: metabase
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: Dockerfile
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_HOST
        value: containers-us-west-23.railway.app
      - key: MB_DB_PORT
        value: 35351
      - key: MB_DB_DBNAME
        value: railway
      - key: MB_DB_USER
        value: shooleu
      - key: MB_DB_PASS
        value: M@reme1994
